# fly.toml app configuration file generated for elp on 2024-05-05T13:12:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "elp"
primary_region = "den"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
